#启动配置端口
server:
  port: 8081

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rain123456
    name: learn
    type: com.zaxxer.hikari.HikariDataSource

  #elasticsearch配置
  elasticsearch:
    rest:
      uris:
        - 127.0.0.1:9200

#mybatis配置
mybatis:
  #扫描mapper路径
  type-aliases-package: com.mybatis.generator.mapper
  #扫描xml文件
  mapper-locations: classpath:mapper/*.xml




